### PR TITLE
Improved README.md

### PR DESCRIPTION
**Pull request by jacktherock**
Hello, I have improved your README.md file, that makes it better and simple to read. If you have any suggestions or want to do any changes in file tell me. I'll fix it. Thank you!

### CODE REVIEW

**Comment by ssine** [comment]
Thanks for your contribution, these modifications look good to me. Would you please tell me why are there `-` marks after titles in line 25 and 34, and colons after latter titles? I have the impression that there shouldn't be punctuations after titles.

**Comment by jacktherock** [comment]
Thanks for your suggestion. I did that marks and colons after titles because I thought it will look more simple than earlier. Now as per suggestion I have been done all the changes that you wanted.

**Comment by ssine** [comment]
merged, thanks

**Comment by jacktherock** [comment]
Thanks

**Comment by jacktherock** [comment]
Hello can you do me a fever, please add hacktoberfest topic to this repo and label my file as _hacktoberfest accepted_ and check [hacktoberfest](https://hacktoberfest.digitalocean.com/hacktoberfest-update) for more info. Thank you!

**Pull request merged**
